/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Admin
 */
public class TrangChu_Panel extends javax.swing.JPanel {

    /**
     * Creates new form TrangChu_Panel
     */
    public TrangChu_Panel() {
        initComponents();
        this.setSize(900, 831);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNen = new javax.swing.JPanel();
        lblCoffee = new javax.swing.JLabel();

        setBackground(new java.awt.Color(219, 147, 7));
        setPreferredSize(new java.awt.Dimension(900, 831));

        pnlNen.setBackground(new java.awt.Color(219, 147, 7));
        pnlNen.setPreferredSize(new java.awt.Dimension(1200, 831));
        pnlNen.setLayout(null);

        lblCoffee.setFont(new java.awt.Font("VNI-Commerce", 0, 72)); // NOI18N
        lblCoffee.setForeground(new java.awt.Color(255, 255, 255));
        lblCoffee.setText("Coffee ABC");
        pnlNen.add(lblCoffee);
        lblCoffee.setBounds(420, 330, 355, 103);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlNen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCoffee;
    private javax.swing.JPanel pnlNen;
    // End of variables declaration//GEN-END:variables
}
